import argparse
import hashlib
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
sys.path[:0] = [str(ROOT / "tools"), str(ROOT / "compiler/tests")]
from check_links import anchors
from conformance import load_support


def validate_documents(root, catalog, data):
    assert set(data) == {"version", "documents"} and data["version"] == 1
    docs = data["documents"]
    base = root / "docs/reference"
    assert set(docs) == {path.relative_to(base).as_posix() for path in base.rglob("*.md")}, "reference inventory drift"
    for name, entry in docs.items():
        assert set(entry) == {"sha256", "evidence", "gap"}, name
        assert entry["sha256"] == hashlib.sha256((base / name).read_bytes()).hexdigest(), f"review changed reference: {name}"
        assert isinstance(entry["gap"], str) and entry["gap"].strip(), f"missing coverage limit: {name}"
        assert isinstance(entry["evidence"], list) and len(set(entry["evidence"])) == len(entry["evidence"]), name
        for item in entry["evidence"]:
            kind, path = item.split(":", 1)
            assert kind in {"native", "checker", "structural", "harness", "schema", "runtime"}, item
            target = (root / path).resolve()
            assert target.is_relative_to(root) and target.is_file(), item
            text = target.read_text()
            assert ("#[test]" in text if target.suffix == ".rs" else "unittest" in text or kind == "schema"), item
    for case in catalog["cases"]:
        path, _, anchor = case["reference"].partition("#")
        assert path.startswith("../reference/"), case["id"]
        name = path.removeprefix("../reference/")
        assert name in docs and (not anchor or anchor in anchors((base / name).read_text())), case["id"]


def cell(value):
    return value.replace("|", "\\|").replace("\n", " ")


def render(catalog, data, gaps):
    cases = catalog["cases"]
    lines = ["# meowy conformance coverage", "",
             "Generated by `python3 -B docs/conformance/coverage.py --write` after reviewing the inventory.", "",
             "This maps evidence and explicit gaps. It is not line/branch coverage or complete language qualification.",
             "Required means the case must pass the runner; it is not a cached execution result. Internal evidence links identify test files, not full document coverage.", "",
             f"{len(data['documents'])} reference documents; {len(cases)} source cases; {len(cases) - len(gaps)} required; {len(gaps)} pinned capability gaps.", "",
             "## Reference inventory", "",
             "Every document retains an explicit remaining gap. Content hashes force a traceability review when reference text changes.", "",
             "| Reference | Required / blocked cases | Internal evidence | Remaining scope |",
             "| --- | --- | --- | --- |"]
    for name, entry in sorted(data["documents"].items()):
        linked = [case for case in cases if case["reference"].partition("#")[0] == "../reference/" + name]
        pending = sum(case["id"] in gaps for case in linked)
        evidence = "; ".join(f"{kind}: [{Path(path).name}](../../{path})" for kind, path in (item.split(":", 1) for item in entry["evidence"])) or "None mapped"
        lines.append(f"| [{name}](../reference/{name}) | {len(linked) - pending} / {pending} | {evidence} | {cell(entry['gap'])} |")
    lines += ["", "## Source contract cases", "", "Unsupported exceptions retain their reference outcomes; B001 never satisfies a language rejection.", "",
              "| Case | Contract | Gate | Reference |", "| --- | --- | --- | --- |"]
    for case in cases:
        expected = case["expected"]
        outcome = ("run " + json.dumps(expected["stdout"]) if case["phase"] == "run" else "accept") if expected["accepted"] else expected["code"]
        status = "Blocked: " + gaps[case["id"]] if case["id"] in gaps else "Required"
        lines.append(f"| [{case['id']}]({case['source']}) | {cell(outcome)} | {cell(status)} | [contract]({case['reference']}) |")
    return "\n".join(lines) + "\n"


def check(root=ROOT, write=False):
    base = root / "docs/conformance"
    catalog = json.loads((base / "cases.json").read_text())
    data = json.loads((base / "documents.json").read_text())
    gaps = load_support(catalog, root / "compiler/tests/conformance_support.json")
    validate_documents(root, catalog, data)
    text = render(catalog, data, gaps)
    report = base / "COVERAGE.md"
    if write:
        report.write_text(text)
    else:
        assert report.read_text() == text, "stale coverage report; review inputs and run coverage.py --write"
    print(f"Validated {len(data['documents'])} reference coverage records; no language execution implied.")


def main():
    parser = argparse.ArgumentParser(description="Validate documentation traceability and render its gap report.")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    check(write=args.write)


if __name__ == "__main__":
    main()
